# Numerical Solution of Non-Linear Equations

In [18]:
import numpy as np
import matplotlib.pyplot as plt

## General real functions

In [19]:
from scipy.optimize import fsolve

In [20]:
def f(x): return x**2 - 1

fsolve(f, 0.5)
fsolve(f, -0.5)
fsolve(f, [-0.5, 0.5])

array([-1.,  1.])

### Example

In [21]:
def f(x): return np.sin(x)**10
fsolve(np.sin, 1)
fsolve(f, 1)
# Close answer, but not exact

/Applications/anaconda3/lib/python3.7/site-packages/scipy/optimize/minpack.py:163: RuntimeWarning: The number of calls to function has reached maxfev = 400.
  warnings.warn(msg, RuntimeWarning)


array([1.88363483e-13])

In [22]:
def f(x): return 1/(x-1)
fsolve(f, 2, full_output = True)

(array([1.76023683e+83]),
 {'nfev': 400,
  'fjac': array([[-1.]]),
  'r': array([1.36716432e-166]),
  'qtf': array([-9.19213804e-84]),
  'fvec': array([5.68105374e-84])},
 2,
 'The number of calls to function has reached maxfev = 400.')

## Complex roots of polynomials

In [23]:
def f(x): return x * (1 + x**3) -1
fsolve(f, 1), fsolve(f, -1)
# Two real roots and two complex roots

(array([0.72449196]), array([-1.22074408]))

In [24]:
np.roots([1, 0, 0, 1, -1])

array([-1.22074408+0.j        ,  0.24812606+1.03398206j,
        0.24812606-1.03398206j,  0.72449196+0.j        ])